name: Windows (clang-cl)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install latest LLVM
        shell: pwsh
        run: choco install llvm -y --no-progress

      - name: Configure
        run: cmake --preset clang-cl
      - name: Build
        run: cmake --build --preset clang-cl
      - name: Test
        run: ctest --preset clang-cl
